### ISSUE TITLE
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Companies'.

### ISSUE THREAD

**Issue by monelge** [kodlamaio-projects/nArchitecture#134]
cli uzerinden etity için crud işlemlerini oluşturdum.
![image](https://github.com/kodlamaio-projects/nArchitecture/assets/33961151/7536bc30-d5fe-4872-8cc0-42a2c286200b)

swager üstünden test etmek istediğimde ise her ne yaptıysam contextimi düzenlediysemde sürekli şu hatayı almaktayım 
Microsoft.Data.SqlClient.SqlException (0x80131904): Invalid object name 'xxxxxxxxxxxxx'.

![image](https://github.com/kodlamaio-projects/nArchitecture/assets/33961151/01a10286-5fb1-4acf-ad60-e8c23c3880de)

dbcontextim 
 ```
public static IServiceCollection AddPersistenceServices(this IServiceCollection services, IConfiguration configuration)
 {
     services.AddDbContext<BaseDbContext>(options => options.UseSqlServer(configuration.GetConnectionString("BaseDb")));
     services.AddScoped<ICompanyRepository, CompanyRepository>();
     return services;
 }
```

**Comment by halitkalayci** [comment]
Can you migrate your db and make sure your latest changes are there.

`Add-Migration migration_name`
`Update-Database`

**Comment by ahmet-cetinkaya** [comment]
You can re-open the issue, if you think the problem persists.
