### ISSUE TITLE
users controller'da GetFromAuth endpointinde userId gelmiyor

### ISSUE THREAD

**Issue by yasartaymaz** [kodlamaio-projects/nArchitecture#137]
projemde postgresql kullanıyorum.
migration ve update database yapıldı. login endpointinden default user ile giriş yapıyorum. tokeni alıp swaggerda authorize kutusuna basına Bearer ekleyip user sekmesinden GetFromAuth calıstırıyorum. user dont exist diyor. debug ettigimde ise userid ve diger detaylar null veya 0 olarak geliyor. acaba atladıgım bir nokta mı var. detaylar aşagıda:

users controller'da GetFromAuth endpointinde userId gelmiyor. getUserIdFromRequest metodundan 0 olarak geliyor.
action metodunun içinde kendim elle aşagıdaki gibi httpcontext.user'a ulasmaya calısıyorum ama oradan da null sonuc geliyor.

```
var user = HttpContext.User;
var userId = user.FindFirst(ClaimTypes.NameIdentifier)?.Value;
var username = user.Identity.Name;
var userId2 = User.FindFirstValue(ClaimTypes.NameIdentifier);
```

**Comment by yasartaymaz** [comment]
userscontroller.GetFromAuth tarafındaki ss1:
![Ekran görüntüsü 2023-09-29 202526](https://github.com/kodlamaio-projects/nArchitecture/assets/9800077/f9d04a88-c87b-44e4-85b7-e9697f5cd965)

userscontroller.GetFromAuth tarafındaki ss2:![Ekran görüntüsü 2023-09-29 202543](https://github.com/kodlamaio-projects/nArchitecture/assets/9800077/229c7651-1469-4c76-8533-c810bf16c591)

basecontroller.getUserIdFromRequest ss1:
![Ekran görüntüsü 2023-09-29 202654](https://github.com/kodlamaio-projects/nArchitecture/assets/9800077/9fe39576-ca85-4d9f-aedb-477dc4f42698)

**Comment by yasartaymaz** [comment]
ekleme:
ayrıca yeni bir proje generate ettim generator ile. yeni bir postgresql dbye bagladım. yine aynı sonuc. 
sonra yeni bir proje daha generate ettim. bu sefer direk inmemoryden calıstırdım. yine userId gelmiyor.
jwt'nin içindeki detaylar httpcontext.user'a aktarılmıyor.

**Comment by yasartaymaz** [comment]
postmanden istek atınca sorunsuz calısıyor. lakin swagger tokeni girmemize rağmen göndermiyor. bundan dolayı yukarıdaki sorunlarla karşılaşılıyor.

**Comment by ahmet-cetinkaya** [comment]
Swagger'a token'ı nasıl eklediğine dair ekran görüntüsü paylaşır mısın?
