### ISSUE TITLE
nArchitecture yapıda IoC nerede tanımlanmalı?

### ISSUE THREAD

**Issue by xXAvoraXx** [kodlamaio-projects/nArchitecture#138]
Merhaba, DependencyResolvers hangi katmanın altında tanımlanmalı? CorePackages içerisinde yerleştirmek istiyorum fakat webapi projesi içerisinde ki Infrastructure katmanının varlığı kafamı karıştırıyor. CorePackages içerisinde tanımladığım DependencyResolver'ı tüm webapi projelerimin kullanmasını değişkenlik gösterenleri ise docker configurationu veya appsettings içindeki configuration'a göre çözümlesin veya çözümlemesinin kararını vereceğim bir yapıya çevirmek istiyorum. Eğer webapi projesindeki Infrastructure altında tanımlarsam aynı kodu diğer web servisleri içerisinde'de tanımlamam gerekir, tam olarak mantığıma yerleştiremedim.

**Comment by ahmet-cetinkaya** [comment]
Öncelikle, cevabımın gecikmesi için kusura bakmayın 🙌. Her katmanın kendi bağımlılıkları ve sorumlulukları vardır. Bu nedenle, her katmanda kendi ServiceRegistration dosyasına sahibiz ve ilgili katmanların bağımlılık çözümlerini bu dosyalar üzerinde tanımlayabilirsiniz. Başlatılabilir projede, örneğin WebAPI, bu ServiceRegistration dosyaları aracılığıyla bağımlılıkları IoC konteynerine ekleriz. İsterseniz ilgili ServiceRegistration dosyasında IConfiguration örneğini alabilir ve ilgili konfigürasyonlara göre bağımlılıkları düzenleme işlemlerini gerçekleştirebilirsiniz.

**Comment by xXAvoraXx** [comment]
Core.Packages projesini şu şekilde yeniden tasarladım,

Onion mimarisine göre tüm katmanları çözümlere ayırdım.

- Application
- Domain
- Infrastructure
- Persistence

Persistence ve Infrastructure katmanı içerisindeki sabit tanımları Domain katmanına aktardım. Persistence katmanındaki Entity tanımlamaları vesayre Domain katmanı içerisinde. Exception türlerinide Domain katmanına aldım, bunu alma sebebim Onion mimarisine göre tüm servislerin ve arayüzlerin Application katmanında tanımlanması gerektiği.

Core.Application.Infrastructure.Abstractions adında bir proje oluşturdum ve arayüzleri buraya aktardım örneğin IRespository, ICacheService vb.

Infrastructure katmanındaki CrossCuttingConcerns projesi ile Persistence projeleri Core.Application.Infrastructure.Abstractions projesine bağımlıdırlar bu sayede Core.Domain katmanına erişerek oradaki gerekli tanımlamalara erişebiliyorlar.

MediaTR ile ilgili pipeline tanımlamalarını Core.Application.API adında bir projeye taşıdım, bu proje Core.Application.Infrastructure.Abstractions projesini referans proje olarak alır.

CrossCuttingConcerns ile Persistence projelerini referans alan bir Core.Packages adında library projesi oluşturmayı ve bu proje içerisinde serviceCollectionExtensions'larını birleştirip paket haline getirdikten sonra ana web api projesinde uygulamanın çekirdeğine yani Domain katmanına eklemeyi düşünüyorum. Ayrıca Core.Application.API diye adlandırdığım projeyide Application katmanına doğrudan referans vereceğim. Sizce izlediğim yol doğru mu?

@ahmet-cetinkaya
