### ISSUE TITLE
DeletedDate İndex Önerisi

### ISSUE THREAD

**Issue by Glipotions** [kodlamaio-projects/nArchitecture#139]
Atılan her sorguda WHERE x."DeletedDate" IS NULL eklendiğini göz önüne alırsak bu kolonu indexlemek mantıklı ve bu indexte de sadece null olanları indexlemesi için 
Sql kodu:
CREATE NONCLUSTERED INDEX Ix_DeleteIndex ON dbo.XTable (DeletedDate) WHERE DeletedDate IS NULL
veya
CREATE INDEX Ix_DeleteIndex ON dbo.XTable (DeletedDate) WHERE DeletedDate IS NULL

EF configuration dosyalarında ise şu yeterli olacaktır:
        builder.HasIndex(e => e.DeletedDate).HasFilter("\"DeletedDate\" IS NULL");

**Comment by ahmet-cetinkaya** [comment]
Öncelikle geç cevabım için kusura bakmayınız. "DeletedDate" sütunu, sadece NULL ve NULL olmayan iki değere sahip olduğu için düşük cardinality'ye sahiptir. Index oluşturmak, bu durumda performansa olumlu bir etki yapmaz. Aksine, işleri yavaşlatabilir veya gereksiz alan kullanımına neden olabilir. Bu nedenle, bu sütunu indexlemek gerekli değildir ve performansa olumlu bir etki yapmayacaktır.
