### ISSUE TITLE
Entity Framework .Net CLI işlemlerinde hataya çözüm 

### ISSUE THREAD

**Issue by SadikSunbul** [kodlamaio-projects/nArchitecture#143]
Diyelimki vs editörümüz yok veya mac bir bilgisayarımız var bu durumda vs da ki Package Manager di sanırım bu olmadığından dolayı .Net CLI kullanarak migratiosn işlemleri yapmamız gerekicek . Buradaki hata da tam olarak bu dur . Aşağıdaki kodu eklerseniz sorun çözülüyor . Sevdiğim bir Code generator olduğu için bunun da sisteme eklenmesini isterim.

 + ```cs
         namespace Persistence.Contexts;

          public class DesingTimeDbContextFactory : IDesignTimeDbContextFactory<BaseDbContext>
          {
              public BaseDbContext CreateDbContext(string[] args)
              {
                  IConfigurationBuilder configurationBuilder = new ConfigurationBuilder();
          
                  string basePath = Path.Combine(Directory.GetCurrentDirectory(), "..", "WebAPI");
                  configurationBuilder.SetBasePath(basePath);
          
                  // appsettings.json dosyasının olduğu yolu ekleyin
                  configurationBuilder.AddJsonFile("appsettings.json");
          
                  IConfiguration configuration = configurationBuilder.Build();
          
                  // appsettings.json içindeki "BaseDb" bağlantı dizesini alın
                  string connection = configuration.GetConnectionString("BaseDb");
          
                  // DbContextOptionsBuilder kullanarak bağlantıyı belirtin
                  DbContextOptionsBuilder<BaseDbContext> dbContextOptionsBuilder = new DbContextOptionsBuilder<BaseDbContext>();
                  dbContextOptionsBuilder.UseSqlServer(connection);
          
                  // BaseDbContext örneğini oluşturun ve bağlantıyı geçirin
                  return new BaseDbContext(dbContextOptionsBuilder.Options);
              }
          }

**Comment by ahmet-cetinkaya** [comment]
Dotnet komutları için Visual Studio kullanmıyorsanız, Dotnet CLI kullanmanız gerekecektir. nArch Gen ise herhangi bir IDE veya editöre bağlı olmadan CLI üzerinden bağımsız çalışır.

Persistence katmanı WebAPI projesinden bağımsız olmalıdır; direkt olarak ilgili klasörünü dosya dizininden alması, yaklaşımımıza uymuyor. Context'leri PersistenceServiceRegistration dosyasında hangi teknolojiyi ve hangi konfigurasyonu kullanacağı gibi teknoloji ve ortam özelliklerini belirleyerek sisteme ekliyoruz.

**Comment by SadikSunbul** [comment]
Ama DesingTimeDbContextFactory bu sınıfı oluşturmaz isem Dotnet CLI den işlem yapamam? neyapmam gerekli peki? başka bir çözümü varmıdır bunun?

**Comment by ahmet-cetinkaya** [comment]
> Ama DesingTimeDbContextFactory bu sınıfı oluşturmaz isem Dotnet CLI den işlem yapamam? neyapmam gerekli peki? başka bir çözümü varmıdır bunun?

`dotnet-ef` toolu ile ilgili EntityFramework işlemlerini cli üzerinden gerçekleştirebilirsiniz. Şahsen ben de bu şekilde kullanmaktayım.
