### ISSUE TITLE
narchgen generate crud (Hatası)

### ISSUE THREAD

**Issue by SadikSunbul** [kodlamaio-projects/nArchitecture#145]
Projede yeni bir sınıf oluşturalım. İsimlendirme kısmında dikkat edilmesi gereken bir durum var. Oluşturduğumuz sınıfların isimlerinin sonuna sadece sayı ekleniyor, örneğin: Deneme2 gibi. Sonrasında "narchgen generate crud" komutu ile generate işlemine başlayalım. İçeride istediğimizi seçerek oluşturun.
Ancak, şu bir hata var: "narchgen generate crud" komutunu çalıştırdığımızda, Application/Features altında dosya oluştururken normalde Deneme2s yapmasını bekleriz. Ancak bu, doğru şekilde yapılmıyor ve sadece Deneme2 olarak oluşturuluyor. Bu durum, domain içindeki referansı karıştırarak hata almamıza neden oluyor.

**Comment by ahmet-cetinkaya** [comment]
nArch Gen isimlerin çoğul ifadelerini dinamik bir şekilde belirler. Bunun için öncelikle class isimlerinin İngilizce olması gerekir. İngilizce tarafındaki çoğul ifade eki kurallarına göre dinamik bir şekilde çoğul kelimesini belirlemektedir.
