### ISSUE TITLE
Core packages esnekliği

### ISSUE THREAD

**Issue by Glipotions** [kodlamaio-projects/nArchitecture#153]
Öncelikle emeğinize sağlık bana faydası dokunuyor.
Projeyi geliştiriyorsunuz bu da çok güzel bir şey ancak son geliştirmeler ile ilgili şöyle bir problemim var; önceden core paketleri de proje içinde olduğu için üzerinde oynamalar yaparak kendimize göre değiştirebiliyorduk ancak şu an nuget paketi olarak yayımlandığı için bu esneklik kaybolmuş görünüyor. önceki şekilde olması bence daha sağlıklı olacaktır. iyi günler dilerim.

**Comment by ahmet-cetinkaya** [comment]
Merhaba,

NuGet ile daha iyi bir paket yönetimi ve güncelleme mekanizması sağlayabiliyoruz. Dilerseniz [NArchitecture.Gen v0.1.0 sürümünü](https://www.nuget.org/packages/Kodlamaio.nArchGen/0.1.0/) kullanmaya devam edebilirsiniz. Alternatif olarak, [Core projelerini](https://github.com/kodlamaio-projects/nArchitecture.Core) harici olarak projenize ekleyebilirsiniz.
