### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by hamzagoksal61** [kodlamaio-projects/nArchitecture#154]
Merhaba,

Proje MongoDB destekliyor mu ?

İyi Çalışmalar

**Comment by ahmet-cetinkaya** [comment]
`src/starterProject/Persistence/PersistenceServiceRegistration.cs` dosyası üzerinden Entity Framework için istediğiniz veri tabanı yönetim sistemini konfigüre edebilirsiniz.
